# Generated by Django 5.2.1 on 2025-05-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rank',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
